
name: Pipeline

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python $ {{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-verison }}
    - name: Install dependencies
      run: |
        make install
        make install-test
    - name: Lint
      run: |
        make lint-check
    - name: Test
      run: |
        make test-unit
  test:
    name: Test Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      - name: Build images
        run: |
          make docker-build
      - name: Run container
        run: |
          make docker-run
      - name: Poll Hosts
        run: |
          make docker-poll
      - name: Install Locust
        run: |
          make install-test
      - name: Run Locust
        run: |
          make test-locust

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO }}:latest
