name: Locust Test

on: [push]

jobs:
  test:
    name: Test Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      - name: Build images
        run: |
          make docker-build
      - name: Run container
        run: |
          docker-run
      - name: Poll Hosts
        run: |
          docker-poll
      - name: Install Locust
        run: |
          make install-test
      - name: Run Locust
        run: |
          test-locust
